### ISSUE TITLE
merge in the fix for callee bug 

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#11]
ebuchman/eris-contracts.js

Fixes the callee issue which happens with new tendermint.

(noting for lib week)

**Comment by rguikers** [comment]
Any chance you are referring to this error?. 

../../node_modules/eris-contracts/lib/pipes/dev_pipe.js:101
                callback(null, data.call_data.callee);
                                             ^
TypeError: Cannot read property 'callee' of undefined

Does this have to do with erisdb version used?

Thanks,

**Comment by NodeGuy** [comment]
Please create a pull request.
