### ISSUE TITLE
Event data appears to be duplicated across blocks

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#12]
When getting events from a contract the number of events triggered per block is correct but all data is the same for all events triggered in that block.

**Comment by androlo** [comment]
is it the same with indexed fields as with non indexed? had an issue myself where non indexed fields were the same, but indexed ones are properly updated.

**Comment by dennismckinnon** [comment]
It is happening for indexed arguments. Per your suggestion I only used indexed arguments.

```
	event event1(uint indexed indexnum, uint indexed EID);
	event event2(uint indexed indexnum, uint indexed EID);
	event event3(uint indexed indexnum, uint indexed EID);
```

Indexnum refers to which object is being updated and EID is a counter which increments on every event emitted or triggered.

The behaviour I see is I am sticking 5 transactions into a block at a time and I get 5 events back butthe data will be like

{indexnum: 45837, EID: 5}
{indexnum: 45837, EID: 5}
{indexnum: 45837, EID: 5}
{indexnum: 45837, EID: 5}
{indexnum: 45837, EID: 5}

I will try to write a test to demonstrate this behaviour.

**Comment by dennismckinnon** [comment]
I can't seem to produce a minimal example yet. I'll keep trying by adding some busy work to the function calls.

**Comment by dennismckinnon** [comment]
Closing because I was unable to reproduce a minimal test case and now think this issue is coming from elsewhere.
