### ISSUE TITLE
contracts returning strings don't work because utils.js toUtf8 is broken

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-contracts.js#17]
The utility function to decode a string returned by a contract is broken causing the value to always be undefined.

the method

```
var toUtf8 = function(hex) {
// Find termination
    var str = "";
    var i = 0, l = hex.length;
    if (hex.substring(0, 2) === '0x') {
        i = 2;
    }
    for (; i < l; i+=2) {
        var code = parseInt(hex.substr(i, 2), 16);
        str += String.fromCharCode(code);
    }
    // TODO find out why this is weird.
    return hexToAscii(str);
};
```

should be

```
var toUtf8 = function(hex) {
    // TODO find out why this is weird.
    return hexToAscii(hex);
};
```

**Comment by rlaveycal** [comment]
The fromUtf8() method is also doing double encoding:

```
var fromUtf8 = function(str) {
    return asciiToHex(str);
    var hex = "";
    for(var i = 0; i < str.length; i++) {
        var n = str.charCodeAt(i).toString(16);
        hex += n.length < 2 ? '0' + n : n;
    }

    return hex;
};
```

and should be:
```
var fromUtf8 = function(str) {
    return asciiToHex(str);
};
```

**Comment by NodeGuy** [comment]
Please try the fix in the beta and let me know if it works for you:

`npm install eris-contracts@beta`

**Comment by rlaveycal** [comment]
Returning strings works but sending them fails

```
[JSON RPC 2.0 Error] Message Id: 4, (INVALID_PARAMS) - encoding/hex: invalid byte: U+0058 'X'
Error callback from sendTransaction
```

contracts is:
```
    function setAndGetString(string s) constant returns (string){
        return s;
    }
```

**Comment by NodeGuy** [comment]
Ethan, would you please confirm this failure in your test harness?

**Comment by ebuchman** [comment]
I can replicate using `eris-contracts@beta`, but if I just use `eris-contracts` then the `setAndGetString` solidity contract works fine for me

**Comment by NodeGuy** [comment]
@rlaveycal would you please submit a test case for your bug?

**Comment by rlaveycal** [comment]
The contract contains:

```
    function getString() constant returns (string){
        return "hello";
    }
```

- 0.13.1 returns ``` undefined ```
- 0.13.2 beta returns ``` hello ``` (but fails for the case above)

**Comment by ebuchman** [comment]
Can you tell us how you're compiling the solidity? Do you have a solc installed locally, or using a remote service?

**Comment by NodeGuy** [comment]
Richard believes this is a bug in upstream and will file an issue there.

**Comment by rlaveycal** [comment]
I'm using the default eris remote service compiler...but I think this is a byte/string coding/decoding issue (see above)

**Comment by NodeGuy** [comment]
Fixed.
