### ISSUE TITLE
Calling 'constant' functions on a contract should be possible via a synchronous call

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-contracts.js#18]
It is currently required to pass a callback to any invocation of a contract function.
This asynchronicity is not always required or even desired. Contract functions that are declared as 'constant' or automatically generated access functions for 'public' data fields should allow provide an optional synchronous invocation alternative.

**Comment by dennismckinnon** [comment]
This behaviour would be considered very bad practice in node. Asynchronous calls should always be used for operations like file reading and database access. The only exceptions would be if you could guarantee that there would be no concurrent execution going on or if you wished to ensure blocking the entire application until the request came back (which would once again be considered very bad practice) If you want to achieve that behaviour you should use the async library which offers many functions which can make asynchronous functions behave like synchronous ones without the side effect of blocking the entire application.

**Comment by j-h-scheufen** [comment]
@dennismckinnon I agree. However, I was in a situation when it was necessary to call multiple functions to retrieve data and found it an obstacle to synchronize when all are done.
Are you saying the 'async' library has tools to overcome that? If so, I was not aware of it and will give it a try and close this ticket.

**Comment by j-h-scheufen** [comment]
Invalid. see prior comments
