### ISSUE TITLE
npm install eris-contracts.js not working on windows

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-contracts.js#22]
A colleague of mine was unable to post an issue, so I post it for him.

Note that the attached file was `.log`, but was renamed to `.txt` for it to be allowed to be attached.

He's using Windows and tried to install `eris-contracts.js` and it is not working.

Is it known not to work on Windows?

[npm-debug.txt](https://github.com/eris-ltd/eris-contracts.js/files/152343/npm-debug.txt)

**Comment by NodeGuy** [comment]
To install on Windows successfully, here's what I had to do first:

Install:
 * Node.js
 * Git
 * Python version 2 (not 3!)
 * Visual Studio Community 2015 Edition
  * Select `Custom`/`Programming Languages`/`Visual C++`

Set the environment variable `GYP_MSVS_VERSION` to `2015`.

Your log shows the error `Could not resolve hostname github.com: Name or service not known`.  Perhaps your colleague's Internet connection wasn't working?

**Comment by kootenpv** [comment]
He confirmed he got it working, thanks!
