### ISSUE TITLE
Allow switching contract address quickly

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-contracts.js#24]
I'm now using quite a lot of code to constantly switch between which contract to use. Rob mentioned something was available in the module, though not exported.

It would be great if switching between target contracts would be super easy.

**Comment by NodeGuy** [comment]
Would you mind sharing your code?

**Comment by kootenpv** [comment]
I refactored my code today using a Promise, and such that I can have a static factory address (from epm.json deployed).

    function getContract(account, issueName) {
        return new Promise(function(resolve, reject) {
            factory.getContractByName(erisC.utils.padRight(erisC.utils.asciiToHex(issueName), 64), function(error, result) {
                contractData = require(epmPath);
                contractName = "Issue";
                rfcAbi = JSON.parse(fs.readFileSync(expandHomeDir("~/.eris/apps/simplechain/abi/" + contractName)));
                contractsManager = erisC.newContractManagerDev(erisdbURL, accountData[account]);
                resolve(contractsManager.newContractFactory(rfcAbi).at(result))
            });
        });
    }

For every call I want to make on a contract, I first use the above code, followed by the code below:

    getContract(req.user.alias, issueName)
            .then((x) => x.getStatus()   // where getStatus is a function on a contract

I guess it works fine for now, though it would be nice if it would be more straightforward.
Node is not my main language, so perhaps you have suggestions.

**Comment by dennismckinnon** [comment]
@NodeGuy this is basically what I was talking about in our call the other day

**Comment by NodeGuy** [comment]
Agreed; this will be super easy with the new API.
