### ISSUE TITLE
[Feature Request] Better handling of input (and output) arguments.

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#31]
For example

bytes32 is a static type so if data is input for an argument that is longer then 32 bytes the javascript should either truncate it or produce a helpful error message from the javascript level. failing to do so will cause an unhelpful error message being passed up from the EVM.

Bytes32 should be able to be passed in as a buffer (hex encoded string should still be supported) - this one is kind of obvious but it only makes sense since a bytes object in javascript is a buffer. We should probably also discuss if return values of bytes32 should be buffers (i'm leaning towards yes however addresses should still be hex-encoded strings)

General output format. I think returns should be in json objects. this has some complexity due to the fact that returns do not need to be named. I think is all returns are named we should return as a json object otherwise array of values?

**Comment by NodeGuy** [comment]
> bytes32 is a static type so if data is input for an argument that is longer then 32 bytes the javascript should either truncate it or produce a helpful error message from the javascript level. failing to do so will cause an unhelpful error message being passed up from the EVM.

Implemented in the new API wrapper.

> We should probably also discuss if return values of bytes32 should be buffers (i'm leaning towards yes however addresses should still be hex-encoded strings)

Yes they should.  A hex-encoded string can be derived from a buffer like so: `buffer.toString('hex')`

> General output format. I think returns should be in json objects. this has some complexity due to the fact that returns do not need to be named. I think is all returns are named we should return as a json object otherwise array of values?

The new API wrapper handles return values like this:

Single values are passed straight through, e.g. `42` is `42`.

Multiple values, e.g., `(24, 42)`, are returned as an array `[24, 42]`.

Named returns are accessible via their names:

Solidity:
```
            function get() constant returns (uint, uint retVal) {
                return (24, 42);
            }
```

JavaScript:
```
          assert.equal(value[0], 24)
          assert.equal(value[1], 42)
          assert.equal(value.retVal, 42)
```
