### ISSUE TITLE
[Feature request] Watch event logs from the beggining of the blockchain

### ISSUE THREAD

**Issue by TinoSM** [eris-ltd/eris-contracts.js#32]
Hi,

This is a feature request from someone using web3 on Ethereum (or at least started implementing this in an Ethereum private network).

I currently have a contract which has inputs (aka transactions) which are simply reflected as "balance" for a user, however these inputs have a meaning by themselves and looking to the history is good for auditing purposes (as they reflect real time events).

What I mean is that looking at events' history is actually useful for me, I don't want to use them just to trigger balance updates.

What I would like to do is to be able to transform:

myContract.RegisteredTransaction(stubFunc, callbackFun).

to:

myContract.RegisteredTransaction({}, {fromBlock: 0}, callbackFun);

So I can get all events from the past and also future ones.

I'll perform a workaround which is basically saving this information in an array, however I feel that this is a dirtier way (and maybe less scaling? not sure) than just looking at the log.

Thanks beforehand,

PS: Linked with https://support.erisindustries.com/support/tickets/319

**Comment by NodeGuy** [comment]
This is a feature request for Eris DB.
