### ISSUE TITLE
TypeError: this._erisdb.txs is not a function

### ISSUE THREAD

**Issue by billieluxu** [eris-ltd/eris-contracts.js#33]
Error occurred when trying to deploy contracts to a chain using Eris-contracts.js library. 

The chain setup is simple, 3 nodes(1 validator), please find the node in the slack group. Here are the details of the error thrown: 

at DevPipe.transact (/Users/Billie/.eris/apps/myapp/node_modules/eris-contracts/lib/pipes/dev_pipe.js:92:18)
at ContractFactory.new (/Users/Billie/.eris/apps/myapp/node_modules/eris-contracts/lib/contractManager.js:157:20)

**Comment by NodeGuy** [comment]
Hi Billie,

Thanks for the report.  Please copy the details of your setup from the Slack group to here.

Also, it looks like the error was truncated—I see only two lines of a stack trace above with no error message.  Can you paste more of the original message?

**Comment by billieluxu** [comment]
Hi David,

The setup of the test is very simple, one validator and two participants.

The full description of the error:
TypeError: this._erisdb.txs is not a function
    at DevPipe.transact (/Users/Billie/.eris/apps/test/node_modules/eris-contracts/lib/pipes/dev_pipe.js:92:18)
    at ContractFactory.new (/Users/Billie/.eris/apps/test/node_modules/eris-contracts/lib/contractManager.js:157:20)
    at test (/Users/Billie/.eris/apps/test/test.js:54:26)
    at Object.<anonymous> (/Users/Billie/.eris/apps/test/test.js:75:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)

**Comment by NodeGuy** [comment]
Thank you Billie.  I need to see your code in order to attempt to replicate the error.  Please attach it here.

**Comment by billieluxu** [comment]
Hi David, here's the js code for deploying contracts:

`// requires
var fs = require ('fs');

var erisC = require('eris-contracts');
var solc = require('solc');

// NOTE. On Windows/OSX do not use localhost. find the
// url of your chain with:
// docker-machine ls
// and find the docker machine name you are using (usually default or eris).
// for example, if the URL returned by docker-machine is tcp://192.168.99.100:2376
// then your erisdbURL should be http://192.168.99.100:1337/rpc
var erisdbURL = "http://192.168.99.100:1337/rpc";

// get the abi and deployed data squared away
var contractData = require('./epm.json');
var mainContractAddress = contractData["deployStorageK"];
var abi = JSON.parse(fs.readFileSync("./abi/" + mainContractAddress));

// properly instantiate the contract objects manager using the erisdb URL
// and the account data (which is a temporary hack)
var accountData = require('./accounts.json');
// var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.mychain_full_000);

var pipe = new erisC.pipes.DevPipe(erisdbURL, accountData.testchain_full_000);
var contractManager = erisC.newContractManager(pipe);


// Create a factory for the contract with the JSON interface 'abi'.
var myContractFactory = contractManager.newContractFactory(abi);

//source of the smart contract
var contractSource = fs.readFileSync("./base.sol", 'utf8');

//compile smart contract code
var output = (solc.compile(contractSource, 1));
var myCompiledCode;

for (var contractName in output.contracts) {
	// code and ABI that are needed by web3 
	myCompiledCode=output.contracts[contractName].bytecode;
	
}

// console.log(myCompiledCode);

function test() {



	//for(var i=0; i<=10000; i++) {


	  	myContractFactory.new({data: myCompiledCode}, function(error, contract){

	    	if(error) {throw error}
	    	
	    	console.log(contract);

	  

		}); 

	// }
	 
}

// run
test();
`
