### ISSUE TITLE
Transferring tokens from one user address to another

### ISSUE THREAD

**Issue by getsachmail** [eris-ltd/eris-contracts.js#35]
when we are using address.send(uint param) in Solidity it is transferring one token from address (given at time of eris pkg do --address param value i.e. -the account from where we deploy the contract) to the deployed contract's address, irresepective of any amount, it only transfers one token. 

<<<<<<<<<<<<<<<<<<<<<<<<tran.sol>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
contract tran {

    function transfer(address ge, uint amount) returns (bool result) 
    {
        return ge.send(msg.value);
    }    

    function getBalance() returns (uint bal) 
    {
        return this.balance; // balance is "inherited" from the address type
    }    
}

<<<<<<<<<<<<<<<<<<<<<<<<app.js>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
var fs = require ('fs');
var binstring = require('binstring');

// Get 'eris-contracts'. 
var erisContracts = require('eris-contracts');
 
// Get 'eris-db' (the javascript API for eris-db) 
var erisdbModule = require("eris-db");
 
 var erisdbURL = "http://192.168.99.100:1337/rpc";

// Create a new instance of ErisDB that uses the given URL. 
var erisdb = erisdbModule.createInstance(erisdbURL);
// The private key. 
//var accountData = require('/some/account/data.json');
var accountData = require('./accounts.json');
 
// Create a new pipe.  
var pipe = new erisContracts.pipes.DevPipe(erisdb, accountData.simplechain_full_000);

pipe.addAccount(accountData.simplechain_root_000);
pipe.addAccount(accountData.simplechain_root_001);

var contractManager = erisContracts.newContractManager(pipe);

var contractData = require('./epm.json');
var idisContractAddress = contractData["deployStorageK"];
var myJsonAbi  = JSON.parse(fs.readFileSync("./abi/" + idisContractAddress));
var myContractFactory = contractManager.newContractFactory(myJsonAbi);

myContractFactory.at(idisContractAddress, function(error, contract){
    if(error) {throw error}
    myContract = contract;
    //console.log(myContract);
}); 

    myContract.getBalance(function(error, result)
    {
        if(error)
        {
            throw error;
        }
        console.log("Before Contract address account balance");
        console.log(result);
    });

    myContract.transfer("ED6469F715EA4E99427402FEA1E45544C814E3A0", 1000000,function(error, result)
    {
        if(error)
        {
            throw error;
        }
        console.log("Before Contract address account balance");
        console.log(result);
    });    

    myContract.getBalance(function(error, result)
    {
        if(error)
        {
            throw error;
        }
        console.log("After Contract address account balance");
        console.log(result);
    });

**Comment by NodeGuy** [comment]
There are many reasons why this is failing.  Here are the first three I see:

- `getBalance` should be declared `constant`:

```Solidity
function getBalance() constant returns (uint bal) 
{
    return this.balance; // balance is "inherited" from the address type
}
```

The `transfer` function is ignoring the `amount` argument.  Did you mean to write this?

```Solidity
function transfer(address ge, uint amount) returns (bool result) 
{
    return ge.send(amount);
}
```

Your asynchronous JavaScript functions are executing synchronously.  They should be written like this instead:

```JavaScript
      myContract.getBalance(function(error, result)
      {
          if(error)
          {
              throw error;
          }
          console.log("Before Contract address account balance");
          console.log(result);

          myContract.transfer("ED6469F715EA4E99427402FEA1E45544C814E3A0", 1000000,function(error, result)
          {
              if(error)
              {
                  throw error;
              }
              console.log("Before Contract address account balance");
              console.log(result);

              myContract.getBalance(function(error, result)
              {
                  if(error)
                  {
                      throw error;
                  }
                  console.log("After Contract address account balance");
                  console.log(result);
              });
          })
      })
```

I'm closing this issue because it's not pinpointing a bug in our code.  Feel free to re-open it if you find a bug after fixing your own.
