### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#36]
Have been getting this with node version 6

http://pastebin.com/4Fa3wZBC

its non-breaking right now as the program still runs but I can't figure out what the relevant pieces of the dump are.

**Comment by NodeGuy** [comment]
Thank you.  Since I'm rewriting the libraries from scratch this may become a non-issue by the time Node.js 6 is official.  I'm closing the issue for now.
