### ISSUE TITLE
[eris-contracts] Error when calling contract function: 'Error: No account address provided, and no default account has been set."

### ISSUE THREAD

**Issue by AdamScislowicz** [eris-ltd/eris-contracts.js#37]
Reproduction Steps:

1. Follow the ERIS tutorial to produce a simplechain and key, and export that key.

2. Create the following smart contract

contract EmailGenerator {
        event LogEmail(string indexed from, string indexed to, string subject, string body);

        function generateEmail(string from, string to, string subject, string body) {
                LogEmail(from, to, subject, body);
        }

        function () {
                throw; // do no accept ether
        }
}

3. Create the following application using javascript:

// requires
var fs = require('fs');
var prompt = require('prompt');
var erisC = require('eris-contracts');

// erisdb, abi, and deployed data
var erisdbURL = "http://localhost:1337/rpc";
var contractData = require('./epm.json');
var emailGeneratorAddr = contractData["deployEmailGenerator"];
var emailGeneratorAbi = JSON.parse(fs.readFileSync("./abi/" + emailGeneratorAddr));

// contract objects manager via erisdb and account data
var accountData = require('./accounts.json');
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.simple_chain_full_000);

var emailGenerator = contractsManager.newContractFactory(emailGeneratorAbi).at(emailGeneratorAddr);
emailGenerator.generateEmail("from@addr", "to@addr", "subject line", "body text", function(error, data) {
        if (error) {
                throw error;
        }
});

4. create a package.json

{
  "name":         "EmailGeneratorApp",
  "version":      "0.0.1",
  "dependencies": {
    "eris-contracts": "^0.13.1",
    "mandrill-api": "1.0.45",
    "prompt": "*"
  }
}

5. run 'npm install'

6. attempt to run send.js: 'node send.js'

**Comment by AdamScislowicz** [comment]
# eris keys ls
The keys on your host kind marmot             7668CF4E1015E81898C981AE631216BA1CA5B144
The keys in your container kind marmot        1625BF16E3645CE36208E5B61DE399A5D5FB36D9
                                             35C967D3B112EA54CDC248788269FCAB56109A0A
                                             382997ACCBED12F78B798076C11EB184F030E54D
                                             7668CF4E1015E81898C981AE631216BA1CA5B144
                                             8E98E68A690D88AE21317A4F25679E07588BD63F
                                             F83DBD89366468CE45FA45011D7C7B2967CA8240

# cat ~/.eris/chains/simplechain/accounts.json 
{
  "simplechain_full_000": {
    "address": "1625BF16E3645CE36208E5B61DE399A5D5FB36D9",
    "pubKey": "49B1C8774CB3DC3D869B64C7B63E5569A5B838FE0F92C03B389C595ADB90F154",
    "privKey": "BCFC257DC3BC66A4FD140FBE562ACF9A8C2CADBAEFE1450C33535813375FF31749B1C8774CB3DC3D869B64C7B63E5569A5B838FE0F92C03B389C595ADB90F154"
  },
  "simplechain_root_000": {
    "address": "382997ACCBED12F78B798076C11EB184F030E54D",
    "pubKey": "76C9E8D456ACC2A766CC7F625D12122BB216CC8638F0D063292B9B3C2AA22EDB",
    "privKey": "3B6C536C5C440F459433C439F20E46FD2FB7762FE6D37D594ED18A0675F3539F76C9E8D456ACC2A766CC7F625D12122BB216CC8638F0D063292B9B3C2AA22EDB"
  },
  "simplechain_root_001": {
    "address": "8E98E68A690D88AE21317A4F25679E07588BD63F",
    "pubKey": "3D59ABD1F35E1D2D7AA42F608F333AA66ACEA98C278FB1706E9FC26900D9E79A",
    "privKey": "8A6C8D721B712EA2116F899E0B3EFEEDB3E3DB45921F54A2D722B3A105EDD0413D59ABD1F35E1D2D7AA42F608F333AA66ACEA98C278FB1706E9FC26900D9E79A"
  }
}

**Comment by AFDudley** [comment]
Could this be a reserved word/reserved character issue?

**Comment by NodeGuy** [comment]
This line:

```JavaScript
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.simple_chain_full_000);
```

should read:

```JavaScript
var contractsManager = erisC.newContractManagerDev(erisdbURL, accountData.test_chain_full_000);
```
