### ISSUE TITLE
Recommend nvm instead of weird Ubuntu 14.04 setup

### ISSUE THREAD

**Issue by Levino** [eris-ltd/eris-contracts.js#40]
Read up on nvm and replace the ```apt-get install node-legacy``` stuff from the Readme with ```nvm install 4 && nvm use 4```

**Comment by NodeGuy** [comment]
I'm aware of `nvm`.  We recommend installing `node-legacy` because most people expect the Node.js binary to be named `node` instead of `nodejs`, which is [the default in Debian to avoid a naming conflict](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907#108).
