### ISSUE TITLE
TypeError: Cannot read property 'return' of undefined

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-contracts.js#41]
I am running some code on rc3 (installed from released binary on github on Ubuntu 16.04.1 x64, default version on DO) that used to work and get a pretty cryptic error message:

```
/root/.eris/apps/sonect-nodeServer/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98
                callback(null, data.return);
                                   ^

TypeError: Cannot read property 'return' of undefined
    at /root/.eris/apps/sonect-nodeServer/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98:36
    at /root/.eris/apps/sonect-nodeServer/node_modules/eris-db/lib/transactions.js:176:9
    at fixedCallback (/root/.eris/apps/sonect-nodeServer/node_modules/eris-db/lib/unsafe.js:120:13)
    at /root/.eris/apps/sonect-nodeServer/node_modules/eris-db/lib/rpc/http.js:81:13
    at httpRequest.onreadystatechange (/root/.eris/apps/sonect-nodeServer/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/root/.eris/apps/sonect-nodeServer/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/root/.eris/apps/sonect-nodeServer/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/root/.eris/apps/sonect-nodeServer/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by NodeGuy** [comment]
The released version of the JavaScript libraries aren't compatible with the not-yet-released version of Eris DB.

This is the second bug report in a row I've gotten about this.  Did our documentation encourage you to try the pre-release version somewhere?

**Comment by SCBuergel** [comment]
I installed it all from the rc3 released on github release page. Is there any way to get a compatible eris:db and js library? I am not sure which one is which tbh, for now I am back to 0.11.4 which still works. hard to test the rc3 without JS libraries though.

**Comment by benjaminbollen** [comment]
Hi @SCBuergel, currently the integrated testing of the js libraries happens independently of the node, which has allowed for this divergence to occur during the release candidates. We are working to improve this with the actual 0.12.0 release.  In the meantime, Casey's guide monax slack may help you out.  Please add here or on slack if your problem is not resolved.

**Comment by h0ryn** [comment]
Hi - same issue here (posted on slack as well), sticking to stable release while expecting the JS module update you mention there. Thanks a lot!

**Comment by SCBuergel** [comment]
@benjaminbollen @NodeGuy: any update? This is a show stopper for the 0.12.0 release.

**Comment by dennismckinnon** [comment]
@NodeGuy now that 0.12.0 is released do you have a fix for this ready to go? Its also blocking an internal project of high priority

**Comment by joluHo** [comment]
I had the same issue and found a workaround. Take a look at issue #39 
It boils down to deleting the line 119 in unsafe.js which containts 
`data2 = data2[1];`
That worked for me.

**Comment by NodeGuy** [comment]
When 0.12.0 is released on Ubuntu (it isn't yet, [the latest CircleCI build of eris-db.js](https://circleci.com/gh/eris-ltd/eris-db.js/250) is still pulling 0.11.4) I will publish a new version of eris-contracts.js that works with it.

**Comment by NodeGuy** [comment]
Published 0.15.2.

**Comment by tcs166070** [comment]
it failed when i try to install 0.15.2

ubuntu@ip-20-0-4-47:~/.eris/apps/idi$ npm install eris-contracts@0.15.2
ramda@0.22.1 node_modules/eris-contracts/node_modules/@nodeguy/type/node_modules/ramda -> node_modules/eris-contracts/node_modules/@nodeguy/generic/node_modules/ramda
- @nodeguy/generic@1.0.3 node_modules/eris-contracts/node_modules/@nodeguy/type/node_modules/@nodeguy/generic
- @nodeguy/type@0.2.0 node_modules/eris-contracts/node_modules/iteray/node_modules/@nodeguy/type
- iteray@0.5.1 node_modules/eris-contracts/node_modules/iteray
idis_app@0.0.1 /home/ubuntu/.eris/apps/idi
└─┬ eris-contracts@0.15.2  invalid
  ├─┬ @nodeguy/type@0.1.0
  │ └── @nodeguy/generic@1.0.3
  └─┬ eris-db@0.15.2
    └─┬ @nodeguy/type@0.2.0
      └── @nodeguy/generic@2.0.0

npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.
npm WARN idis_app@0.0.1 No description
npm WARN idis_app@0.0.1 No repository field.
npm WARN idis_app@0.0.1 No license field.

**Comment by somak12** [comment]
Same happening for 0.15.6. Please provide some input in this matter. We are stuck because of this versioning issue.

**Comment by NodeGuy** [comment]
This issue is for the error `TypeError: Cannot read property 'return' of undefined`.  Please open another issue if you're having a different problem.

**Comment by somak12** [comment]
sure. Yes the issue TypeError: Cannot read property 'return' of undefined was happening when I used eris-contract 0.13.3 with new eris -0.12.0.
