### ISSUE TITLE
Bytes32 inputs not being padded?

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#42]
This seems to be a new problem (which is strange in itself) that when passed a string of hex characters to a contract function that is expecting bytesX input its not automatically right padded... Not sure if this is a bug or not. but should investigated.

**Comment by NodeGuy** [comment]
Are you seeing this using the `beta` branch?

**Comment by dennismckinnon** [comment]
nope this is behaving properly in beta... closing
