### ISSUE TITLE
Non constant function returns hex string

### ISSUE THREAD

**Issue by nottherealbatman** [eris-ltd/eris-contracts.js#46]
Non Constant function in solidity returns hex string instead of value. (Maybe bug from issue  #45 )
eris-contracts : 0.15.4
eris-db: 0.15.4
eris-cli: 0.12.0

Tested with the following code:

	contract Test{

		string _name;

		function setName(string newname) {
			_name = newname;
		}

		function getNameConstant() constant returns (string) {
			return _name;
		}

		function getName() returns (string) {
			return _name;
		}
	}

JavaScript:

	var myContractFactory = contractManager.newContractFactory(abi);
	myContractFactory.new({data: dat}, function(error, contract){
		if (error) {
			// Something.
			throw error;
		}

		contract.setName('Batman', function(err, batman) {

			contract.getNameConstant(function(err, getNameConstant) {
				console.log('getNameConstant', getNameConstant) // returns getNameConstant Batman

				contract.getName(function(err, getName){
					console.log('getName', getName) // returns getName 0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000830784261746D616E000000000000000000000000000000000000000000000000

				})
			})
		})

	});

**Comment by NodeGuy** [comment]
Fixed in 0.15.5.
