### ISSUE TITLE
Already set string in solidity removes 2 char when returing value

### ISSUE THREAD

**Issue by nottherealbatman** [eris-ltd/eris-contracts.js#47]
Contract:

    contract Test{
		string _withSpace = "  Pieter";
		string _withoutSpace = "Pieter";

		function getWithSpaceConstant() constant returns (string) {
			return _withSpace;
		}

		function getWithoutSpaceConstant () constant returns (string) {
			return _withoutSpace;
		}	
	}

Note the 2 white chars in the `_withSpace ` variable

	var myContractFactory = contractManager.newContractFactory(abi);
	myContractFactory.new({data: dat}, function(error, contract){
		if (error) {
			// Something.
			throw error;
		}
		
		contract.getWithSpaceConstant (function(err, getWithSpaceConstant ) {
			console.log('getWithSpaceConstant ', getWithSpaceConstant ) // getWithSpaceConstant Pieter

			contract.getWithoutSpaceConstant (function(err, getWithoutSpaceConstant ){
				console.log('getWithoutSpaceConstant ', getWithoutSpaceConstant ) // getWithoutSpaceConstant eter

			})
		})

	});

return must be constant or else a hex string will be returned as reported at #46

**Comment by NodeGuy** [comment]
Fixed in 0.15.5.
