### ISSUE TITLE
eris-contracts 0.15.6 installation fails on Windows 10

### ISSUE THREAD

**Issue by the-real-aquaman** [eris-ltd/eris-contracts.js#51]
When trying to install eris-contracts 0.15.6 using npm on Windows, it fails. Didn't have any issues with eris-contracts 0.13.3 on Windows before upgrading.

Error (with npm cache cleaned):
```npm WARN deprecated node-uuid@1.4.7: use uuid module instead
bc-XXXX@0.0.1 C:\workspace\BC_XXXX
`-- (empty)

npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pieter.noyens\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "eris-contracts@0.15.6"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! path C:\workspace\BC_XXXX\node_modules\.staging\@nodeguy\type-245fb8fa
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\workspace\BC_XXXX\node_modules\.staging\@nodeguy\type-245fb8fa' -> 'C:\workspace\BC_XXXX\node_modules\eris-contracts\node_modules\eris-db\node_modules\@nodeguy\type'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\workspace\BC_XXXX\node_modules\.staging\@nodeguy\type-245fb8fa' -> 'C:\workspace\BC_XXXX\node_modules\eris-contracts\node_modules\eris-db\node_modules\@nodeguy\type'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\BC_XXXX\npm-debug.log
```

--Aquaman

**Comment by AFDudley** [comment]
@the-real-aquaman have you resolved this issue yourself?

**Comment by the-real-aquaman** [comment]
@AFDudley Nope, issue still there even after npm cache clean. So returned to my ubuntu vm ;)

**Comment by NodeGuy** [comment]
@pietv It's taking me a while to diagnose the problem here because I'm unfamiliar with Windows.  I'll keep working on it but do you see anything obvious?

**Comment by NodeGuy** [comment]
The blocking bug is intermittent and today I was able to reproduce the original bug briefly.  It may be this npm bug: https://github.com/npm/npm/issues/9633.

**Comment by NodeGuy** [comment]
This is a bug in NPM.  Please use [Yarn](https://yarnpkg.com/) to install eris-contracts instead.

**Comment by NodeGuy** [comment]
We're no longer recommending the use of Yarn in general but it's OK to use it for working around the npm bug on Windows until it's fixed.

**Comment by dharmesh-kh24** [comment]
@NodeGuy Is there any way to install eris-contracts on windows, such that correct dependencies are downloaded? As Yarn does not obey npm-shrinkwrap.json file, I am not able to correctly install eris-contracts. Any help is much appreciated.

**Comment by NodeGuy** [comment]
It's OK to use Yarn.  The `npm-shrinkwrap.json` file is used to tighten up security but it's not required.
