### ISSUE TITLE
Call Method and byte array parameter

### ISSUE THREAD

**Issue by dungtctin4** [eris-ltd/eris-contracts.js#56]
As request of @zramsay , I post question here

In your document 2 Solidity, (https://monax.io/docs/tutorials/solidity/solidity_2_action_driven_architecture/)

I see ActionManager use  actn.call(data); in which data is bytes (byte array) to call many different Actions.
1) **But there are not any "call" method in these Actions so how can this command can reach these actions?**
**How can this  command will call the "execute" method of these two actions belows?
I wil modify this command to become actn.execute(data)?**

2) As you see, **we can have many Actions. Each of them can have different "execute" methods with different parameters in different data type => we must have byte arrays in the ActionManger as generic data type parameter to call the "execute" method of an action.**

Must we change the "execute" method of each action to become like this?
 function execute( bytes data) returns (bool){...}
instead of function execute(address addr, uint amount) returns (bool) {...}

If Yes, how can this "execute" method can resolve or cast its parameters data to obtain necessary value?

**3) From Javascript Node JS or form the file like epm.yaml, we want to send transaction to the "execute" method of ActionManager, how can we cast our value into bytes to send it?**

Thanks a lot

```
// The new action manager.
contract ActionManager is DougEnabled {

  // This is where we keep the "active action".
  address activeAction;

  function ActionManager(){
  }

  function execute(bytes32 actionName, bytes data) returns (bool) {
    address actionDb = ContractProvider(DOUG).contracts("actiondb");
    if (actionDb == 0x0){
      return false;
    }
    address actn = ActionDb(actionDb).actions(actionName);
    // If no action with the given name exists - cancel.
    if (actn == 0x0){
      return false;
    }
    // Set this as the currently active action.
    activeAction = actn;
    // Run the action. Any contract that calls 'validate' now will only get 'true' if the
    // calling contract is 'actn'. Again - no return value check (true/false).
    actn.call(data);
    // Now clear it.
    activeAction = 0x0;
    return true;
  }

}

contract ActionEndow is Action {

  function execute(address addr, uint amount) returns (bool) {
    if(!isActionManager()){
      return false;
    }
    ContractProvider dg = ContractProvider(DOUG);
    address endower = dg.getContract("bank");
    if(endower == 0x0){
      return false;
    }
    Endower(endower).endow(addr, amount);
    return true;
  }
}

contract ActionCharge {

  function execute(address addr, uint amount) returns (bool) {
    if(!isActionManager()){
      return false;
    }
    ContractProvider dg = ContractProvider(DOUG);
    address charger = dg.getContract("bank");
    if(charger == 0x0){
      return false;
    }
    Charger(charger).charge(addr,amount);
    return true;
  }
}
```

**Comment by VoR0220** [comment]
@dungtctin4 Call is a low level function that can be used to simply talk to a contract and their functions. There is without a doubt though, a better way to structure the action driven architecture. Going to be taking a look through the blogs soon and updating them accordingly. Thanks for the reminder to fix this up.

**Comment by dungtctin4** [comment]
Thanks @VoR0220  for your answer. Before updating the documents, could you show me how to use eris-contract.js in my Node JS file in order to send transaction to the "execute" method of ActionManager above? , how can I cast my parameter value into "byte array parameter" in Node JS or in the epm.yaml file

Please note that, the "bytes data" parameter of this "execute method" is correspond to 2 parameters of the function below
` function execute(address addr, uint8 perm) returns (bool)`

**Comment by NodeGuy** [comment]
This Solidity code is over my head.  Can you help, @VoR0220 or @dennismckinnon?

**Comment by VoR0220** [comment]
@dungtctin4 so based on this old setup (which is ancient btw, I really must stress that we need to update this and that if you are a beginner this is not something you should be messing with as it increases the attack surface of solidity dramatically), however, there is a correct way to do this and the rest of the docs keep the rest of it in somewhat good shape. To answer your question, if I were gives one ```bytes``` value and I had to split it that way, I'd fill the bytes using 20 bytes for the address and one byte for the uint8 value. You should be able to pass this in as a hex string in eris-pm in the epm.yaml iirc. Not sure what the corresponding js would be.

**Comment by NodeGuy** [comment]
Here's an example of a hex string in JavaScript: `'00000000000000000000000000000000DEADBEEF'`

**Comment by visa10** [comment]
I'm sorry, but you can set an example
