### ISSUE TITLE
How to write a contract to work with already deployed chain contract and constructor of a contract?

### ISSUE THREAD

**Issue by dungtctin4** [eris-ltd/eris-contracts.js#58]
First questions for smart contract already deployed in the chain

There is a smart contract already deployed on the chain with address Ox.....
Here is its code 
```
contract ContractAlreadyDeployed{
 function function1(parameter1, parameter2) returns (bool res) {
...
 }
 function function2(parameter1, parameter2) returns (bool res) {
...
 }
}
```

This contract is already deployed by another person and **I donot have its source code file on my machine**. I only know its address and I want to use its 2 functions. So How to write a contract to call functions in this already deployed chain contract?

I think of 2 methods. Please verify it to me

1) Method 1
I create an interface with abstract functions that are the same as the contract above:
```
contract ContractAlreadyDeployedInterface{
   function function1(parameter1, parameter2) returns (bool res) ;
   function function2(parameter1, parameter2) returns (bool res) ;
}
```
or/and a contract with empty function

```
contract ContractAlreadyDeployedStubClass{
   function function1(parameter1, parameter2) returns (bool res) {}
   function function2(parameter1, parameter2) returns (bool res) {}
}
```
Each of contracts is stored in 2 files "ContractAlreadyDeployedInterface.sol";, 
"ContractAlreadyDeployedStubClass.sol" in the same directory

Of course, ContractAlreadyDeployed was already deployed before and it doesnot know these two created contracts. 

And then, a contract that works with ContractAlreadyDeployed is created and stored in the file ContractToWorkWithAlreadyDeployedContract.sol in the same directory:

```
import "ContractAlreadyDeployedInterface.sol";
import "ContractAlreadyDeployedStubClass.sol";

contract ContractToWorkWithAlreadyDeployedContract{
  address MyContractAlreadyDeployedAddr = 0x..//address of already deployed contract, hard coded or  injected from exterior by calling function SetAddress below
function SetAddress(address ContractAlreadyDeployedAddr)  {
  MyContractAlreadyDeployedAddr = ContractAlreadyDeployedAddr;
 }


 function CallFunction1(parameter1, parameter2) returns (bool res) {
     res = ContractAlreadyDeployedInterface(MyContractAlreadyDeployedAddr ).Function1(parameter1, parameter2);

  // or

   res = ContractAlreadyDeployedStubClass(MyContractAlreadyDeployedAddr ).Function1(parameter1, parameter2);
 }

function CallFunction2(parameter1, parameter2) returns (bool res) {
res = ContractAlreadyDeployedInterface(MyContractAlreadyDeployedAddr ).Function2(parameter1, parameter2);

  // or

   res = ContractAlreadyDeployedStubClass(MyContractAlreadyDeployedAddr ).Function2(parameter1, parameter2);
 }

}

}
```

In this method 1, ContractAlreadyDeployedStubClass or ContractAlreadyDeployedInterface, Which works? or both of them doesnot works?
If both of them works, Which is better?

2) Method 2:
Create a contract that Inherits the already deployed contract. But I donot know how to do

3) In the method 1 above, I have to put all 3 contract files in the same directory and use "import". 
When I use epm.yaml with command "eris pkgs do" to deploy these 3 contracts, I have only to put the ContractToWorkWithAlreadyDeployedContract.sol in the file epm.yaml because it imports the other 2 contract files and these imported contract files will be automatically deployed?

If these methods are not true, could you tell me how to write contracts to use methods in already deployed contracts? Thanks a lot

**Comment by dungtctin4** [comment]
Another question concerning constructor of a contract:
2 have two contract like below, stored respectively in 2 files *.sol in the same directory:
```
contract Contract1 {

    address owner;

    mapping (address => uint) balances;

    // Constructor
    function Contract1(){
    }

    function setOwner(address newOwner) returns (bool res) {
        if (owner != 0x0 && msg.sender != owner){
            return false;
        }
        owner = newOwner;
        return true;
    }
.......................................
......................................
}


import "Contract1.sol";
contract Contract2 {

    address owner;

    address CurrentContract1;

    // Permissions
    mapping (address => uint) perms;

    // Constructor
    function Contract2(){
        owner = msg.sender;
        CurrentContract1 = new Contract1();
        // NEW
        // *********************************************************************
        Contract1(CurrentContract1).setOwner(address(this));
        // *********************************************************************
    }

    
    function setContract1(address newContract1) returns (bool res) {
        if (msg.sender != owner){
            return false;
        }
        // NEW
        // *********************************************************************
        bool result = Contract1(newContract1).setOwner(address(this));
        // If we couldn't set ourself as owner, we will not add it.
        if(!result){
            return false;
        }
        // *********************************************************************
        CurrentContract1 = newContract1;
        return true;
    }
..................................
..................................
}

```

Here the file epm.yaml to deploy the Contract2:

```
jobs:
- name: deployContract2
  job:
    deploy:
      contract: Contract2.sol
      wait: true

```

When I run eris pkgs do with the file epm.yaml above, 

eris pkgs do --chain simplechain3 --address $addr3_0 --file epm.yaml --abi-path ./abi_for_simplechain3_tmp

I receive the address of the Contract2 but there are not any address of Contract1.
1) Could you tell me whether Constructor of the Contract2 is executed with the command "eris pkgs.." above?
2) If the answer is yes, the owner (msg.sender) of this Contract2 is itself $addr3_0 in the command "eris pkgs..."above? or something else?
3) If the answer is yes, the command in the constructor of this Contract2 "CurrentContract1 = new Contract1();" create new address for Contract1. Why I donot receive this address in the reponse of "eris pkgs do..."
Thanks a lot

**Comment by NodeGuy** [comment]
> So How to write a contract to call functions in this already deployed chain contract?

The standard way to do this requires you to have the ABI and the address of the already-deployed contract:

```JavaScript
contractManager.newContractFactory(abi).at(address, (error, contract) => {
  if (error) {
      throw error
  } else {
    // Use the already-deployed contract here.
  }
})
```

**Comment by NodeGuy** [comment]
@dennismckinnon Would you please answer the second question?

**Comment by NodeGuy** [comment]
Your second question is outside the scope of reporting an issue with this library.  If you'd like more support we encourage you to sign up with our [premium support offering](https://monax.io/packages/).
