### ISSUE TITLE
Fail to obtain address of deployed Contract on the chain in Eris

### ISSUE THREAD

**Issue by dungtctin4** [eris-ltd/eris-contracts.js#59]
Hello
I have a chain with 2 full nodes + 2 root nodes.
2 full nodes runs at 2 machines and all is good. I have a code below:
I only use code below to deploy dynamically a contract on the chain, but I cannot obtain the address of deployed contract

```
const node_host = "localhost";
const default_rpc_port = "1337";

const chain_name ="mychain_name";
const chain_name_directory_path ="../chains";
const json_account_file_name = "accounts.json";

var contractCode = "contract SimpleContract { \n" + 
                     "uint storedData;" + "\n" + 
                    "function set(uint x) {storedData = x;} " + "\n" + 
                    "function get() constant returns (uint retVal) { return storedData;}}";

var output = Solidity.compile(contractCode,1);//1 to activate the optimiser
var compiledSimpleContract = output.contracts.SimpleContract;
var abiSimpleContract = JSON.parse(compiledSimpleContract.interface);
var bytecodeSimpleContract = compiledSimpleContract.bytecode;

var MyNewContractAddress;


//********it doesnot run***************
getContractManager().then(function(contractManager) {
  var contractFactory = contractManager.newContractFactory(abiSimpleContract);
  log("contractFactory from getContractManager = \n " + contractFactory);
   contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
     if (error){throw error;}

     MyNewContractAddress = contract;

     log("Using promise------------------------");
   });

});
log("MyNewContractAddress: " + MyNewContractAddress); //output: undefined
//***********************

function getContractManager() {

    return new Promise(function(resolve, reject) {
	var accountData = require(chain_name_directory_path + "/" + chain_name + "/" + json_account_file_name);
        //log("getContractManager");

	//var contractManager = erisContracts.newContractManagerDev(dbUrl, accountData.irt_testchain2_full_000);
	var contractManager = erisContracts.newContractManagerDev(dbUrl, accountData[chain_name + "_full_000"]);        
        //log(contractManager);
        //log("------------------------");
        resolve (contractManager);
    });
}
```

I have obtained contractManager and I can find i'm successful to deploy this contract by accessing to localhost:46657/list_accounts and I see new address appear

But I cannot obtain address of deployed of this contract in the code above.
The MyNewContractAddress variable has always "undefined" value

I replace the function getManager() with another function getManager2 

```
function getContractManager2() {
   var accountData = require(chain_name_directory_path + "/" + chain_name + "/" + json_account_file_name);
   //log("getContractManager2");
   var contractManager = erisContracts.newContractManagerDev(dbUrl, accountData[chain_name + "_full_000"]);       
   //log(contractManager);
   //log("------------------------");
   return contractManager;
}
```
and use

```
var contractFactory = getContractManager2().newContractFactory(abiSimpleContract);
contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
   if (error){throw error;}

     MyNewContractAddress = contract;

   log("Not using promise------------------------");
});
log("MyNewContractAddress: " + MyNewContractAddress); 
```
I also try without function by
```
var contractManager = erisContracts.newContractManagerDev(dbUrl, accountData[chain_name + "_full_000"]);  
var contractFactory = contractManager.newContractFactory(abiSimpleContract);
```
It doesnot work either

The only difference is that I donot use Promise any more but I receive the same results:
- undefined for  MyNewContractAddress variable
- Error below in both cases

```
home/my_name/.eris/apps/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename

TypeError: Cannot read property 'call_data' of undefined
    at /home/my_name/.eris/apps/node_modules/eris-contracts/lib/pipes/dev_pipe.js:101:36
    at /home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/transactions.js:176:9
    at fixedCallback (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:120:13)
    at /home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:81:13
    at httpRequest.onreadystatechange (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by NodeGuy** [comment]
I suggest you educate yourself more about how to write asynchronous code in JavaScript.  This line is executing before your promise resolves:

```JavaScript
log("MyNewContractAddress: " + MyNewContractAddress); //output: undefined
```

It should be structured more like this:

```JavaScript
getContractManager().then(function(contractManager) {
  var contractFactory = contractManager.newContractFactory(abiSimpleContract);
  log("contractFactory from getContractManager = \n " + contractFactory);
   contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
     if (error){throw error;}

     MyNewContractAddress = contract;
     log("MyNewContractAddress: " + MyNewContractAddress);

     log("Using promise------------------------");
   });

});
```

**Comment by dungtctin4** [comment]
Thanks @NodeGuy  for your answer. I made a mistake when I type above
The function getContractManager use Promise and getContractManager2 is synch function.
Indeed, I've already code below

**getContractManager()**.then(function(contractManager) {
  var contractFactory = contractManager.newContractFactory(abiSimpleContract);
   contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
     if (error){throw error;}

     **MyNewContractAddress = contract;**
     //var result = error ? error : contract;
     //log(result);
     log("MyNewContractAddress: " + MyNewContractAddress);**//output: undefined**
     log("Using promise------------------------");
   });

});

**getContractManager2 is synch function**
var contractFactory = **getContractManager2()**.newContractFactory(abiSimpleContract);
contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
   if (error){throw error;}

     MyNewContractAddress = contract;

   log("Not using promise------------------------");
});
log("MyNewContractAddress: " + MyNewContractAddress);**//output: undefined**

**Comment by NodeGuy** [comment]
Let's focus on getting it to work without promises for now.

Try the following change to your code:

```JavaScript
//getContractManager2 is synch function**
var contractFactory = getContractManager2().newContractFactory(abiSimpleContract);
contractFactory.new({data: bytecodeSimpleContract}, function(error, contract) {
   if (error){throw error;}

     MyNewContractAddress = contract;
     log("MyNewContractAddress: " + MyNewContractAddress);

   log("Not using promise------------------------");
});
```

**Comment by dungtctin4** [comment]
Thanks @NodeGuy 
This is What I done before I try Promise. However, I have just tried again and I receive error as above

_home/my_name/.eris/apps/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename

TypeError: Cannot read property 'call_data' of undefined
    at /home/my_name/.eris/apps/node_modules/eris-contracts/lib/pipes/dev_pipe.js:101:36
    at /home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/transactions.js:176:9
    at fixedCallback (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/unsafe.js:120:13)
    at /home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:81:13
    at httpRequest.onreadystatechange (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/home/my_name/.eris/apps/node_modules/eris-contracts/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)_

**Comment by NodeGuy** [comment]
You're using an old version of eris-contracts.js.  Please upgrade to 0.15.8 and try again.
