### ISSUE TITLE
events returning hex string as arguments

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-contracts.js#60]
Using 0.15.6. Seems to be related to previous problem with functions returning hex values.

With events the arguments are still returning hex in 0.15.6

```{"event":"Pay","address":"000000000000000000000000CF5DD3EF066054721FE42561B11C52180168FE09","args":{"originator":"0x88977A37D05A4FE86D09E88C88A49C2FCF7D6D8F","beneficiary":"0x721584FA4F1B9F51950018073A8E5ECF47F2D3B8","amount":"0","servicename":"0x456E657267790000000000000000000000000000000000000000000000000000","alias":"0x43656E7472616C65207665727761726D696E6700000000000000000000000000","providername":"0x456E65636F000000000000000000000000000000000000000000000000000000"}}```

The address returned is OK, the values in the arguments are mostly addresses, now with 0x prefix. Would expect them to have no prefix

**Comment by NodeGuy** [comment]
This will be fixed in 0.16.
