### ISSUE TITLE
How to retrieve the transaction hash while invoking through eris-contract.js

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-contracts.js#66]
I want to retrieve the transaction hash in the javascript call. 

Im trying to use block.blockhash(block.number) but its not working. 

example: event SomeEvent(uint block,uint time,address sender,address validator,bytes32 hash,bytes data);

SomeEvent(block.number,block.timestamp,msg.sender,block.coinbase,block.blockhash(block.number),msg.data);

Is there any other way to do that??

**Comment by NodeGuy** [comment]
Please use the issue template for all issues.
