### ISSUE TITLE
Want to fetch the transaction hash form the chain while calling through eris-contract.js

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-contracts.js#68]
Eris version : 0.12.0
eris-contract.js version: 0.15.4

Please refer to https://github.com/eris-ltd/eris-cli/issues/1140 for more details. 

# Issue Description

I want to retrieve the transaction hash in the javascript call.
Im trying to use block.blockhash(block.number) but its not working.
Is there any other way to do that through eris-contract.js??

# Solidity

```Solidity
contract IdisContractsFTW {
  uint storedData;
 event SetEvent(uint block,uint time,address sender,address validator,bytes32 hash,bytes data);


  function set(uint x) {
    storedData = x;
SetEvent(block.number,block.timestamp,msg.sender,block.coinbase,block.blockhash(block.number),msg.data);
  }
  function get() constant returns (uint retVal) {
    return storedData;
  }
}
```

# JavaScript

```JavaScript
// requires
var fs = require ('fs');
var prompt = require('prompt');
var contracts = require('eris-contracts');
var address = "address of the contract.."
var chainUrl = "URL of the chain";
var abi = "abi file here..";

(function () {

    var account = "account used to call the contract..."
    var addressSetSub;
    if (account) {
        // Instantiate the contract object manager using the chain URL and the account data.
        manager = contracts.newContractManagerDev(chainUrl,
            account);

        contract = manager.newContractFactory(abi).at(address);

        contract.SetEvent(startCallback, eventCallback);

        function startCallback(error, eventSub) {
            if (error) {
                throw error;
            }
            addressSetSub = eventSub;
        }
        function eventCallback(error, event) {
            var eventToken = accountLib.getEventToken(event.args.block, event.args.time, event.args.sender, event.args.validator, "ShipItem",event.args.hash, event.args.data);
            //do something with the event token.
        }

    }
    else {
        res.statusCode = 400;
        res.end();
    }
})();
```

**Comment by NodeGuy** [comment]
It doesn't look like you're calling the `set` Solidity method in your JavaScript code.  What do you mean exactly by "its not working"?

**Comment by somak12** [comment]
@NodeGuy  the above code was just an example. I have just shown how i am subscribing to the solidity event in the js code. Please assume that set is already being called. 
As I mentioned in the contract that I want to return the transaction hash as event args by using block.blockhash(block.number). When I use this it gives me an invalid jump error when I call the set solidity method. Does my question make sense or am I missing something here?

**Comment by zramsay** [comment]
@somak12 "invalid jump destination" (the error I assume you are referring to) is the EVM of eris-db's way of saying there's a bug in your solidity code. Debugging solidity is beyond the scope of this repo.

**Comment by somak12** [comment]
@zramsay  ok so this happens when I use block.blockhash(block.number) in my solidity code. That means this option of returning the transaction hash is not right for some reason. So is there any other way of returning  the transaction hash into the javascript?
Similar kind of requirement as returning the transaction hash when calling contract through eris pm

- name: someName
  job:
     call:
        source: MySource
        destination: myDestination
        function: myFunc
        data: [some,data,here]
        save: tx

as @VoR0220  mentioned in https://github.com/eris-ltd/eris-cli/issues/1140

**Comment by VoR0220** [comment]
I'll give him a quick update: try returning it in your function call. Or logging an event with it.

**Comment by somak12** [comment]
I guess that is exactly what im trying to do above. I have logged an event and tried to return the transaction hash as event args. I am using block.blockhash(block.number) to get the transaction hash, but unfortunately this is giving error. So  is there any other way to achieve this?

**Comment by VoR0220** [comment]
Hmmm. Tell you what. Just to get you off of this issue because this is in fact outside the scope of the repo. Hit me up in the Marmot den slack in the about-solidity thread or in the apps-js thread. This sounds like it may be a bug on the db side.
