### ISSUE TITLE
If input types are incorrect an error should be passed in the callback

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#7]
I was just debugging a situation where I would have something like

```
contract.isAdmin.call(address, function(error, output){
	if (error) cb(error, null);
	cb(null, output.values.ret)
});
```
can the callback was not being called. No error was being passed instead an uncaught exception kept appearing "undefined is not a function" of course isAdmin.call was a function it turned out the argument i was passing in address had a string in it and not an address.

Having an uncaught exception makes these situations difficult to work with. (Yes I should have run my own type checks or something but still the callback should still be called with an error to handle it gracefully.)

**Comment by androlo** [comment]
I can't be a full param check in each function to guard against every possible error. If it is unclear how a function should be called, or if there are optional params, then I'll try and be more clear in the docs, though that will be handled case-by-case.

**Comment by dennismckinnon** [comment]
I think you misunderstood this is not with the library functions its with the generated solidity functions. The input type matching is something you already do. Im just asking that a useful error is passed to the callback if the arguments fail to match inputs.

**Comment by androlo** [comment]
There's no explicit check of parameters types. If the the formatting happens to throw an error, for whatever reason, it will catch it and return it in the callback. That's all. If you want to make sure that you're passing the correct data in

**Comment by androlo** [comment]
... Unit test your code

**Comment by dennismckinnon** [comment]
Thats what im saying. The callback was not called at all. It just throws an uncaught undefined is not a function and stops execution

**Comment by dennismckinnon** [comment]
Let me try to make this more clear lets say in solidity I have a function

```
	function addAdmin(address target) returns (bool success){
		//test for admin permissions
		if (isAdmin(msg.sender) == false) return false;

		admin[target] = true;
		return true;
	}
```

this is going to have an abi entry like:
```
{
     "constant":false,
     "inputs":[{"name":"target","type":"address"}],
     "name":"addAdmin",
     "outputs":[{"name":"success","type":"bool"}],
     "type":"function"
}
```

So if I call
```
contract.isAdmin.call(target, function(error, output){
    if (error) cb(error, null);
    cb(null, output.values.success)
});
```

but "target" is not an address (If instead its something inconvertible to the address type such as a string "dennis") the callback is NOT called with an error. the callback is not called AT ALL. Instead an uncaught exception in `contract.isAdmin.call()` is thrown saying "undefined is not a function"  which is clearly not the error that is really occurring.

I'm not asking for checks on every input argument. I'm asking that if the input formatters fail to format that the callback is called with a meaningful error message,

And for the record I found this bug BECAUSE I WAS  unit testing.

**Comment by androlo** [comment]
then pass it an address? i don't see what the issue here is. you don't pass a javascript method the proper number of arguments its behavior will generally be undefined. if you're worried about users calling your methods which passes them on un-checked to support libs, add the guards yourself.

here. maybe this will help: https://www.commonsensemedia.org/app-reviews/kodable-pro

**Comment by dennismckinnon** [comment]
You said yourself that errors from the input formatters are passed to the callback. I'm telling you that its not happening the callback is not being called with the error. If I pass a function a value and its not able to handle it properly it should still pass the error to be handled. the function is defined but its throwing an error instead of passing one.

**Comment by androlo** [comment]
if you don't call it with the right number of params the behavior is undefined. undefined means it does not have a clear behavior. it could return an error, it could not, it could throw an error. it could do nothing. that's how javascript methods generally works, since javascript is not a strongly typed language. That is not a bug, that is the default behavior unless you change it - which i'm not going to do, because it's extra work and it's just stupid hand-holding. send it the correct number of parameters and you'll be fine. if it's unclear how the function in question works, then I will see if the docs needs changing.

don't open this issue again. never open an issue in a github repository in a repo not managed by yourself if the actual manager(s) has closed it. that's extremely annoying, but then again - you're extremely annoying. if you think an issue has been closed wrongly, then explain why and ask to have it re-opened.

**Comment by dennismckinnon** [comment]
It has been closed incorrectly because its a bug. You clearly have not been listening its not that im not sending it the right number of parameters. Its that the parameter types can not be interpretted by  by the input formatters.

Since you would rather attack me personally then look into it ill do it myself.

**Comment by androlo** [comment]
if the formatters produce an error, you get the error in the callback.

**Comment by dennismckinnon** [comment]
then something is going wrong because in the above passing something that can't be converted to an address. like "dennis" causes an error to be thrown and the callback not called (at all. with or without and error)

Hence Bug.

**Comment by androlo** [comment]
Fine. Give me a reproducible example then, and I'll look at it. Both the call and transact methods should catch errors during formatting and send them to the callback function, given that the correct number of  params are used. If that is not true i will bug-flag it again.

re-opening.

**Comment by androlo** [comment]
hahaha wow. i got this all backwards it seems. except one thing....

**Comment by dennismckinnon** [comment]
To be fair to you. I am unable to replicate the exact same code in a new application. I'm looking into the npm dependencies (I have run npm update and it didn't fix it) so I think it might be a dependency of one of the dependencies not getting updated. I have run into this issue before when running npm update. just going to nuke the node_modules folder and re install.

Closing because I can't reproduce in fresh installs. Behaviour as for described situation appears to be as expected.
