### ISSUE TITLE
Make startCallback optional in events

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-contracts.js#9]
Since this is only really used to get the subscription object which will allow you to stop the event listener, If I don't care about stopping it I don't see a reason to have to put in the function(err, obj){return} to fill the space (Its ok to switch the order of the start and event callbacks in order to make this happen.

I put "Enchancement" as the label because this repo doesn't have a "Feature Request" label yet

**Comment by androlo** [comment]
It is optional but if you leave it out it's the same as using `contract.someEvent.once(...)`, meaning it will shut down automatically after receiving the first event. I don't know what the hell is going on with the docs here. I'm 100% sure I've written it at some point, but it's not there. 

I'll go over it today. Sorry.

**Comment by androlo** [comment]
(that and changing 'stopCallback' to 'eventCallback')

**Comment by dennismckinnon** [comment]
cool
